version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_AI: ${USE_AI:-false}
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - USE_AI=${USE_AI:-false}
    command: >
      /bin/sh -c "
        rm -rf ./logs/* &&
        python src/main.py
      "